package vista.inicio;

import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import javax.swing.JOptionPane;

public class IniciarSesionV extends javax.swing.JFrame {

    public IniciarSesionV() {
        initComponents();
        initStyles();
    }
    
    private void initStyles() {
        this.jBiniciarSesion.putClientProperty("JButton.buttonType", "roundRect");
        this.jBsalir.putClientProperty("JButton.buttonType", "roundRect");
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        barra = new javax.swing.JLabel();
        inicioSesion = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        interfaz = new javax.swing.JPanel();
        fondoTitulo = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        contrasenia = new javax.swing.JLabel();
        jCBservidores = new javax.swing.JComboBox<>();
        servidor = new javax.swing.JLabel();
        jPFcontrasenia = new javax.swing.JPasswordField();
        jBiniciarSesion = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barra.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        barra.setForeground(new java.awt.Color(0, 0, 0));
        barra.setText("______________________________");
        background.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 180, 20));

        inicioSesion.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        inicioSesion.setForeground(new java.awt.Color(0, 0, 0));
        inicioSesion.setText("Inicio De Sesion");
        background.add(inicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 170, 30));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.jpg"))); // NOI18N
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 96, 50));

        interfaz.setBackground(new java.awt.Color(215, 195, 205));

        fondoTitulo.setBackground(new java.awt.Color(34, 20, 10));

        titulo.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("GESTOR DE COFFEE Y GELATO GANCINO");

        javax.swing.GroupLayout fondoTituloLayout = new javax.swing.GroupLayout(fondoTitulo);
        fondoTitulo.setLayout(fondoTituloLayout);
        fondoTituloLayout.setHorizontalGroup(
            fondoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        fondoTituloLayout.setVerticalGroup(
            fondoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoTituloLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        contrasenia.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        contrasenia.setForeground(new java.awt.Color(0, 0, 0));
        contrasenia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contrasenia.setText("Contraseña:");

        jCBservidores.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jCBservidores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "El Puyo", "Quito" }));
        jCBservidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBservidoresActionPerformed(evt);
            }
        });

        servidor.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        servidor.setForeground(new java.awt.Color(0, 0, 0));
        servidor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        servidor.setText("Servidor:");

        jPFcontrasenia.setText("**********");
        jPFcontrasenia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPFcontraseniaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPFcontraseniaFocusLost(evt);
            }
        });
        jPFcontrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPFcontraseniaActionPerformed(evt);
            }
        });

        jBiniciarSesion.setBackground(new java.awt.Color(33, 18, 18));
        jBiniciarSesion.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jBiniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jBiniciarSesion.setText("Iniciar Sesion");
        jBiniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBiniciarSesionActionPerformed(evt);
            }
        });

        jBsalir.setBackground(new java.awt.Color(255, 102, 102));
        jBsalir.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jBsalir.setForeground(new java.awt.Color(255, 255, 255));
        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout interfazLayout = new javax.swing.GroupLayout(interfaz);
        interfaz.setLayout(interfazLayout);
        interfazLayout.setHorizontalGroup(
            interfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, interfazLayout.createSequentialGroup()
                .addGroup(interfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPFcontrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(jCBservidores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(84, 84, 84))
            .addGroup(interfazLayout.createSequentialGroup()
                .addGroup(interfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fondoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(interfazLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(interfazLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(servidor, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(interfazLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(interfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBiniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        interfazLayout.setVerticalGroup(
            interfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(interfazLayout.createSequentialGroup()
                .addComponent(fondoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(servidor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBservidores, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPFcontrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jBiniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        background.add(interfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 400, 420));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu.jpg"))); // NOI18N
        background.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCBservidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBservidoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBservidoresActionPerformed

    private void jBiniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBiniciarSesionActionPerformed
        if (new String(this.jPFcontrasenia.getPassword()).equals("P@ssw0rd")){
            db.DataBase.servidorGlobal = this.jCBservidores.getSelectedIndex();
            JOptionPane.showMessageDialog(this, "¡Credenciales correctas!", "Inicio de Sesion", JOptionPane.INFORMATION_MESSAGE);
            vista.inicio.MenuV menu = new MenuV();
            menu.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "¡Credenciales incorrectas!", "Inicio de Sesion", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBiniciarSesionActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jPFcontraseniaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPFcontraseniaFocusLost
        if (new String(this.jPFcontrasenia.getPassword()).isEmpty()) {
            this.jPFcontrasenia.setText("**********");
        }
    }//GEN-LAST:event_jPFcontraseniaFocusLost

    private void jPFcontraseniaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPFcontraseniaFocusGained
        if (new String(this.jPFcontrasenia.getPassword()).equals("**********"))
        this.jPFcontrasenia.setText("");
    }//GEN-LAST:event_jPFcontraseniaFocusGained

    private void jPFcontraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPFcontraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPFcontraseniaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatArcOrangeIJTheme.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesionV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel barra;
    private javax.swing.JLabel contrasenia;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel fondoTitulo;
    private javax.swing.JLabel inicioSesion;
    private javax.swing.JPanel interfaz;
    private javax.swing.JButton jBiniciarSesion;
    private javax.swing.JButton jBsalir;
    private javax.swing.JComboBox<String> jCBservidores;
    private javax.swing.JPasswordField jPFcontrasenia;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel servidor;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
