package vista.inicio;

import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;

public class Menu extends javax.swing.JFrame {

    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPbackground = new javax.swing.JPanel();
        jLlogo = new javax.swing.JLabel();
        jLlinea = new javax.swing.JLabel();
        jLmenu = new javax.swing.JLabel();
        jPgestor = new javax.swing.JPanel();
        jPtitulo = new javax.swing.JPanel();
        jLtitulo = new javax.swing.JLabel();
        jBempleado6 = new javax.swing.JButton();
        jBempleado7 = new javax.swing.JButton();
        jLempleado = new javax.swing.JLabel();
        jBempleado = new javax.swing.JButton();
        jLempleado1 = new javax.swing.JLabel();
        jBempleado1 = new javax.swing.JButton();
        jLempleado2 = new javax.swing.JLabel();
        jBempleado2 = new javax.swing.JButton();
        jLempleado3 = new javax.swing.JLabel();
        jBempleado3 = new javax.swing.JButton();
        jLempleado4 = new javax.swing.JLabel();
        jBempleado4 = new javax.swing.JButton();
        jLempleado5 = new javax.swing.JLabel();
        jBempleado5 = new javax.swing.JButton();
        jLbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPbackground.setBackground(new java.awt.Color(255, 255, 255));
        jPbackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.jpg"))); // NOI18N
        jPbackground.add(jLlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 96, 50));

        jLlinea.setForeground(new java.awt.Color(0, 0, 0));
        jLlinea.setText("________________");
        jPbackground.add(jLlinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 180, 20));

        jLmenu.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLmenu.setForeground(new java.awt.Color(0, 0, 0));
        jLmenu.setText("Menu");
        jPbackground.add(jLmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 170, 30));

        jPgestor.setBackground(new java.awt.Color(153, 153, 153));

        jPtitulo.setBackground(new java.awt.Color(0, 0, 0));

        jLtitulo.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLtitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLtitulo.setText("Menu Principal");

        jBempleado6.setBackground(new java.awt.Color(255, 102, 102));
        jBempleado6.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jBempleado6.setForeground(new java.awt.Color(0, 0, 0));
        jBempleado6.setText("Cerrar Sesion");
        jBempleado6.setBorder(null);

        jBempleado7.setBackground(new java.awt.Color(255, 102, 102));
        jBempleado7.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jBempleado7.setForeground(new java.awt.Color(0, 0, 0));
        jBempleado7.setText("Salir");
        jBempleado7.setBorder(null);

        javax.swing.GroupLayout jPtituloLayout = new javax.swing.GroupLayout(jPtitulo);
        jPtitulo.setLayout(jPtituloLayout);
        jPtituloLayout.setHorizontalGroup(
            jPtituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPtituloLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jBempleado6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jBempleado7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPtituloLayout.setVerticalGroup(
            jPtituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPtituloLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPtituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBempleado6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPtituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBempleado7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        jBempleado.setBackground(new java.awt.Color(255, 102, 51));
        jBempleado.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jBempleado.setForeground(new java.awt.Color(0, 0, 0));
        jBempleado.setText("Empleado");
        jBempleado.setBorder(null);

        jBempleado1.setBackground(new java.awt.Color(255, 102, 51));
        jBempleado1.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jBempleado1.setForeground(new java.awt.Color(0, 0, 0));
        jBempleado1.setText("Empleado");
        jBempleado1.setBorder(null);

        jBempleado2.setBackground(new java.awt.Color(255, 102, 51));
        jBempleado2.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jBempleado2.setForeground(new java.awt.Color(0, 0, 0));
        jBempleado2.setText("Empleado");
        jBempleado2.setBorder(null);

        jBempleado3.setBackground(new java.awt.Color(255, 102, 51));
        jBempleado3.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jBempleado3.setForeground(new java.awt.Color(0, 0, 0));
        jBempleado3.setText("Empleado");
        jBempleado3.setBorder(null);

        jBempleado4.setBackground(new java.awt.Color(255, 102, 51));
        jBempleado4.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jBempleado4.setForeground(new java.awt.Color(0, 0, 0));
        jBempleado4.setText("Empleado");
        jBempleado4.setBorder(null);

        jBempleado5.setBackground(new java.awt.Color(255, 102, 51));
        jBempleado5.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jBempleado5.setForeground(new java.awt.Color(0, 0, 0));
        jBempleado5.setText("Empleado");
        jBempleado5.setBorder(null);

        javax.swing.GroupLayout jPgestorLayout = new javax.swing.GroupLayout(jPgestor);
        jPgestor.setLayout(jPgestorLayout);
        jPgestorLayout.setHorizontalGroup(
            jPgestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPgestorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPgestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPgestorLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLempleado2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBempleado2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPgestorLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLempleado4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBempleado4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPgestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPgestorLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPgestorLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPgestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPgestorLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLempleado3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBempleado3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPgestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBempleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBempleado5, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPgestorLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPgestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLempleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLempleado5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37))
        );
        jPgestorLayout.setVerticalGroup(
            jPgestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPgestorLayout.createSequentialGroup()
                .addComponent(jPtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPgestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPgestorLayout.createSequentialGroup()
                        .addComponent(jLempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBempleado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPgestorLayout.createSequentialGroup()
                        .addComponent(jLempleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBempleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPgestorLayout.createSequentialGroup()
                        .addComponent(jLempleado2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBempleado2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPgestorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPgestorLayout.createSequentialGroup()
                        .addComponent(jLempleado3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBempleado3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPgestorLayout.createSequentialGroup()
                        .addComponent(jLempleado4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBempleado4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPgestorLayout.createSequentialGroup()
                        .addComponent(jLempleado5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBempleado5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 44, Short.MAX_VALUE))
        );

        jPbackground.add(jPgestor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 800, 450));

        jLbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu.jpg"))); // NOI18N
        jPbackground.add(jLbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatArcOrangeIJTheme.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBempleado;
    private javax.swing.JButton jBempleado1;
    private javax.swing.JButton jBempleado2;
    private javax.swing.JButton jBempleado3;
    private javax.swing.JButton jBempleado4;
    private javax.swing.JButton jBempleado5;
    private javax.swing.JButton jBempleado6;
    private javax.swing.JButton jBempleado7;
    private javax.swing.JLabel jLbackground;
    private javax.swing.JLabel jLempleado;
    private javax.swing.JLabel jLempleado1;
    private javax.swing.JLabel jLempleado2;
    private javax.swing.JLabel jLempleado3;
    private javax.swing.JLabel jLempleado4;
    private javax.swing.JLabel jLempleado5;
    private javax.swing.JLabel jLlinea;
    private javax.swing.JLabel jLlogo;
    private javax.swing.JLabel jLmenu;
    private javax.swing.JLabel jLtitulo;
    private javax.swing.JPanel jPbackground;
    private javax.swing.JPanel jPgestor;
    private javax.swing.JPanel jPtitulo;
    // End of variables declaration//GEN-END:variables
}
