package vista.operacion;

import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.DAODetalleVentaImpl;
import persistencia.DAOVentaImpl;

public class DetalleVentaV extends javax.swing.JFrame {
    models.VentaM venta;
    
    public DetalleVentaV() {
        initComponents();
        initStyles();
    }
    
    public DetalleVentaV(models.VentaM venta) {
        initComponents();
        initStyles();
        loadProductoTable();
        this.venta = venta;
    }

    private void initStyles() {
        this.jBsalir.putClientProperty("JButton.buttonType", "roundRect");
        this.jTextPrecioUnitario.putClientProperty("JTextField.placeholderText", "No es obligatorio");
    }
    
    private void loadProductoTable() {
        try {
            persistencia.DAOProductoImpl daoProd = new persistencia.DAOProductoImpl();
            DefaultTableModel model = (DefaultTableModel) this.jTableProductos.getModel();
            daoProd.leer().forEach((prod) -> model.addRow(new Object[]{prod.getId_producto(), prod.getNombre(), prod.getPrecio_base()}));
            
        } catch (Exception e) {
            System.out.println("El siguiente error se ha suscitado: " + e.toString());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPbackground = new javax.swing.JPanel();
        jLlogo = new javax.swing.JLabel();
        jLbarraSelecc = new javax.swing.JLabel();
        jLmenu1 = new javax.swing.JLabel();
        jBsalir = new javax.swing.JButton();
        jLmenu2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProductosAgregados = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextCantidad = new javax.swing.JTextField();
        jTextPrecioUnitario = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jBTerminarFacTotal = new javax.swing.JButton();
        jBVolverVenta = new javax.swing.JButton();
        jBAgregar = new javax.swing.JButton();
        jLbarraSelecc1 = new javax.swing.JLabel();
        jLbarraSelecc2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPbackground.setBackground(new java.awt.Color(255, 255, 255));
        jPbackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.jpg"))); // NOI18N
        jPbackground.add(jLlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 96, 50));

        jLbarraSelecc.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLbarraSelecc.setForeground(new java.awt.Color(255, 255, 255));
        jLbarraSelecc.setText("____________________________________");
        jPbackground.add(jLbarraSelecc, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 230, 20));

        jLmenu1.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLmenu1.setForeground(new java.awt.Color(204, 204, 204));
        jLmenu1.setText("NUEVA VENTA");
        jPbackground.add(jLmenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 170, 30));

        jBsalir.setBackground(new java.awt.Color(255, 102, 102));
        jBsalir.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jBsalir.setForeground(new java.awt.Color(255, 255, 255));
        jBsalir.setText("Salir");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });
        jPbackground.add(jBsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 160, 35));

        jLmenu2.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLmenu2.setForeground(new java.awt.Color(255, 255, 255));
        jLmenu2.setText("Detalle de la Venta");
        jPbackground.add(jLmenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 210, 30));

        jTableProductosAgregados.setBackground(new java.awt.Color(153, 153, 153));
        jTableProductosAgregados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PRODUCTO", "NOMBRE", "PRECIO FINAL", "CANTIDAD"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableProductosAgregados);
        if (jTableProductosAgregados.getColumnModel().getColumnCount() > 0) {
            jTableProductosAgregados.getColumnModel().getColumn(1).setResizable(false);
            jTableProductosAgregados.getColumnModel().getColumn(2).setResizable(false);
        }

        jPbackground.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 450, 250));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CANTIDAD");

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("PRECIO UNITARIO");

        jTextCantidad.setBackground(new java.awt.Color(255, 255, 255));
        jTextCantidad.setForeground(new java.awt.Color(0, 0, 0));

        jTextPrecioUnitario.setBackground(new java.awt.Color(255, 255, 255));
        jTextPrecioUnitario.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(jTextPrecioUnitario))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jPbackground.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 450, 100));

        jTableProductos.setBackground(new java.awt.Color(153, 153, 153));
        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PRODUCTO", "NOMBRE", "PRECIO BASE"
            }
        ));
        jScrollPane3.setViewportView(jTableProductos);

        jPbackground.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 450, 250));

        jBTerminarFacTotal.setBackground(new java.awt.Color(255, 102, 102));
        jBTerminarFacTotal.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jBTerminarFacTotal.setForeground(new java.awt.Color(255, 255, 255));
        jBTerminarFacTotal.setText("TERMINAR FACTURA TOTAL");
        jBTerminarFacTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTerminarFacTotalActionPerformed(evt);
            }
        });
        jPbackground.add(jBTerminarFacTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, -1, -1));

        jBVolverVenta.setBackground(new java.awt.Color(255, 102, 102));
        jBVolverVenta.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jBVolverVenta.setForeground(new java.awt.Color(255, 255, 255));
        jBVolverVenta.setText("VOLVER A VENTA");
        jBVolverVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverVentaActionPerformed(evt);
            }
        });
        jPbackground.add(jBVolverVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 510, -1, -1));

        jBAgregar.setBackground(new java.awt.Color(255, 102, 102));
        jBAgregar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jBAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jBAgregar.setText("AGREGAR");
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });
        jPbackground.add(jBAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, -1, -1));

        jLbarraSelecc1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLbarraSelecc1.setForeground(new java.awt.Color(255, 255, 255));
        jLbarraSelecc1.setText("__________________________________________________________________");
        jPbackground.add(jLbarraSelecc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 400, 20));

        jLbarraSelecc2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLbarraSelecc2.setForeground(new java.awt.Color(255, 255, 255));
        jLbarraSelecc2.setText("__________________________________________________________________");
        jPbackground.add(jLbarraSelecc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, 400, 20));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Lista de Productos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPbackground.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 450, 30));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Lista de Productos agregados a la venta");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPbackground.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 450, 30));

        jLbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo_Gestion.jpg"))); // NOI18N
        jPbackground.add(jLbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jBTerminarFacTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTerminarFacTotalActionPerformed
        int numProd = this.jTableProductosAgregados.getRowCount();
        if (numProd == 0) {
            JOptionPane.showMessageDialog(this, "Debe haber al menos un producto", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        BigDecimal monto_total = BigDecimal.ZERO;
        for (int i = 0; i < numProd; i++) {
            try {
                BigDecimal precio = new BigDecimal(this.jTableProductosAgregados.getValueAt(i, 2).toString());
                BigDecimal cantidad = new BigDecimal(this.jTableProductosAgregados.getValueAt(i, 3).toString());

                monto_total = monto_total.add(precio.multiply(cantidad));  
            } catch (NumberFormatException | NullPointerException e) {
                JOptionPane.showMessageDialog(this, "Error en los datos de la tabla", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        this.venta.setFecha();
        this.venta.setMonto_total(monto_total);
        try {
            DAOVentaImpl daoVenta = new DAOVentaImpl();
            daoVenta.registrar(venta);
            DAODetalleVentaImpl daoDetVent = new DAODetalleVentaImpl();
            
            for (int i = 0; i < numProd; i++) {
                models.DetalleVentaM detVenta = new models.DetalleVentaM();
                detVenta.setId_detalle(Integer.parseInt(String.valueOf(this.venta.getId_venta()) 
                        + String.valueOf(this.jTableProductosAgregados.getValueAt(i, 0).toString())));
                detVenta.setId_sucursal(this.venta.getId_sucursal());
                detVenta.setId_venta(this.venta.getId_venta());
                detVenta.setId_producto(Integer.parseInt(this.jTableProductosAgregados.getValueAt(i, 0).toString()));
                detVenta.setCantidad(Integer.parseInt(this.jTableProductosAgregados.getValueAt(i, 3).toString()));
                detVenta.setPrecio_unitario(new BigDecimal(this.jTableProductosAgregados.getValueAt(i, 2).toString()));
                
                daoDetVent.registrar(detVenta);
            }
            JOptionPane.showMessageDialog(this, "Venta registrada exitosamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (Exception e) {
            System.out.println("El siguiente error se ha suscitado: " + e.toString());
        }
    }//GEN-LAST:event_jBTerminarFacTotalActionPerformed

    private void jBVolverVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverVentaActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBVolverVentaActionPerformed

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        int locProd = this.jTableProductos.getSelectedRow();
        if (locProd == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String cantidad = this.jTextCantidad.getText();
        if (cantidad.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Rellene el campo de cantidad", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String precio_u = this.jTextPrecioUnitario.getText();
        BigDecimal precio_f = BigDecimal.ZERO;
        if (precio_u.isEmpty()) {
            precio_f = new BigDecimal(this.jTableProductos.getValueAt(locProd, 2).toString());
        } else {
            precio_f = new BigDecimal(precio_u);
        }
        
        DefaultTableModel model = (DefaultTableModel) this.jTableProductosAgregados.getModel();
        model.addRow(new Object[]{this.jTableProductos.getValueAt(locProd, 0), 
            this.jTableProductos.getValueAt(locProd, 1), precio_f, cantidad});
    }//GEN-LAST:event_jBAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatArcOrangeIJTheme.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalleVentaV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBTerminarFacTotal;
    private javax.swing.JButton jBVolverVenta;
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLbackground;
    private javax.swing.JLabel jLbarraSelecc;
    private javax.swing.JLabel jLbarraSelecc1;
    private javax.swing.JLabel jLbarraSelecc2;
    private javax.swing.JLabel jLlogo;
    private javax.swing.JLabel jLmenu1;
    private javax.swing.JLabel jLmenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPbackground;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTable jTableProductosAgregados;
    private javax.swing.JTextField jTextCantidad;
    private javax.swing.JTextField jTextPrecioUnitario;
    // End of variables declaration//GEN-END:variables
}
