package vista.operacion;

import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.DAOInventarioMateriaPrimaImpl;
import vista.inicio.MenuV;
import models.InventarioMateriaPrimaM;
import persistencia.DAOEmpleadoImpl;

public class InventarioV extends javax.swing.JFrame {

    public InventarioV() {
        initComponents();
        initStyles();
        jBmodificar.setEnabled(false);
        jBeliminar.setEnabled(false);
    }

    private void initStyles() {
        this.jBmenu.putClientProperty("JButton.buttonType", "roundRect");
        this.jBsalir.putClientProperty("JButton.buttonType", "roundRect");
    }
    
    private void loadTable() {
        try {
            DAOInventarioMateriaPrimaImpl dao = new DAOInventarioMateriaPrimaImpl();
            DefaultTableModel model = (DefaultTableModel) this.jTableInventario.getModel();
            dao.leer().forEach((emp) -> model.addRow(new Object[]{emp.getId_inventario(), emp.getId_sucursal(), emp.getId_materia_prima(), emp.getCantidad_disponible()}));
            
        } catch (Exception e) {
            System.out.println("El siguiente error se ha suscitado: " + e.toString());
        }
    }
    
    private void limpiarCampos() {
    jTextID.setText("");
    jTextSucursal.setText("");
    jTcantidaddisponible.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPbackground = new javax.swing.JPanel();
        jLlogo = new javax.swing.JLabel();
        jLbarraSelecc = new javax.swing.JLabel();
        jLmenu1 = new javax.swing.JLabel();
        jBmenu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTcantidaddisponible = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextSucursal = new javax.swing.JTextField();
        jBañadir = new javax.swing.JButton();
        jBmodificar = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jBsalir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableMateriaPrima = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableInventario = new javax.swing.JTable();
        jLbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPbackground.setBackground(new java.awt.Color(255, 255, 255));
        jPbackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.jpg"))); // NOI18N
        jPbackground.add(jLlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 96, 50));

        jLbarraSelecc.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLbarraSelecc.setForeground(new java.awt.Color(255, 255, 255));
        jLbarraSelecc.setText("__________________________________________________");
        jPbackground.add(jLbarraSelecc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, 20));

        jLmenu1.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLmenu1.setForeground(new java.awt.Color(255, 255, 255));
        jLmenu1.setText("Inventario de Materia Prima");
        jPbackground.add(jLmenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 320, 30));

        jBmenu.setBackground(new java.awt.Color(255, 102, 102));
        jBmenu.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jBmenu.setForeground(new java.awt.Color(255, 255, 255));
        jBmenu.setText("Menu");
        jBmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmenuActionPerformed(evt);
            }
        });
        jPbackground.add(jBmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 160, 35));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista de Inventario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPbackground.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 430, 40));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Lista de Materia Prima");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPbackground.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 440, 40));

        jLabel3.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel3.setText("Cantidad Disponible:");

        jTcantidaddisponible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcantidaddisponibleActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel4.setText("ID Inventario:");

        jTextID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIDActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel5.setText("ID Sucursal:");

        jTextSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSucursalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTcantidaddisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTcantidaddisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPbackground.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 440, 110));

        jBañadir.setBackground(new java.awt.Color(255, 102, 102));
        jBañadir.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jBañadir.setForeground(new java.awt.Color(255, 255, 255));
        jBañadir.setText("Añadir");
        jBañadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBañadirActionPerformed(evt);
            }
        });
        jPbackground.add(jBañadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 100, -1));

        jBmodificar.setBackground(new java.awt.Color(255, 102, 102));
        jBmodificar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jBmodificar.setForeground(new java.awt.Color(255, 255, 255));
        jBmodificar.setText("Modificar");
        jBmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodificarActionPerformed(evt);
            }
        });
        jPbackground.add(jBmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, -1, -1));

        jBeliminar.setBackground(new java.awt.Color(255, 102, 102));
        jBeliminar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jBeliminar.setForeground(new java.awt.Color(255, 255, 255));
        jBeliminar.setText("Eliminar");
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });
        jPbackground.add(jBeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 540, -1, -1));
        jPbackground.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 300, 10));

        jBsalir.setBackground(new java.awt.Color(255, 102, 102));
        jBsalir.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jBsalir.setForeground(new java.awt.Color(255, 255, 255));
        jBsalir.setText("SALIR");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });
        jPbackground.add(jBsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 160, 35));

        jTableMateriaPrima.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID MATERIA PRIMA", "NOMBRE", "UNIDAD", "DESCRIPCION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableMateriaPrima);
        if (jTableMateriaPrima.getColumnModel().getColumnCount() > 0) {
            jTableMateriaPrima.getColumnModel().getColumn(0).setResizable(false);
            jTableMateriaPrima.getColumnModel().getColumn(1).setResizable(false);
            jTableMateriaPrima.getColumnModel().getColumn(2).setResizable(false);
            jTableMateriaPrima.getColumnModel().getColumn(3).setResizable(false);
        }

        jPbackground.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 440, 150));

        jTableInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID INVENTARIO", "ID SUCURSAL", "ID MATERIA PRIMA", "CANTIDAD DISPONIBLE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTableInventario);
        if (jTableInventario.getColumnModel().getColumnCount() > 0) {
            jTableInventario.getColumnModel().getColumn(0).setResizable(false);
            jTableInventario.getColumnModel().getColumn(1).setResizable(false);
            jTableInventario.getColumnModel().getColumn(2).setResizable(false);
            jTableInventario.getColumnModel().getColumn(3).setResizable(false);
        }

        jPbackground.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 430, 330));

        jLbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo_Gestion.jpg"))); // NOI18N
        jPbackground.add(jLbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmenuActionPerformed
        MenuV menu = new MenuV();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBmenuActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBsalirActionPerformed

    private void jTcantidaddisponibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcantidaddisponibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcantidaddisponibleActionPerformed

    private void jTextIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIDActionPerformed

    private void jBañadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBañadirActionPerformed
        if (jTextID.getText().trim().isEmpty() || 
        jTextSucursal.getText().trim().isEmpty() ||
        jTcantidaddisponible.getText().trim().isEmpty() ||
        jTableMateriaPrima.getSelectedRow() == -1 || // Verificar si no se ha seleccionado una fila
        jTableMateriaPrima.getValueAt(jTableMateriaPrima.getSelectedRow(), 0) == null || // Verificar si el valor es nulo
        jTableMateriaPrima.getValueAt(jTableMateriaPrima.getSelectedRow(), 0).toString().trim().isEmpty()) { // Verificar si está vacío

        JOptionPane.showMessageDialog(null, "Todos los campos deben estar llenos", "Error", JOptionPane.ERROR_MESSAGE);
        return;
        }

        
        // Validar tipos de datos
        int idEmpleado;
        try {
            idEmpleado = Integer.parseInt(jTextID.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El ID del Empleado debe ser un número entero", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Crear el objeto y asignar valores               
        models.InventarioMateriaPrimaM nuevoInventario = new models.InventarioMateriaPrimaM();
        nuevoInventario.setId_inventario(Integer.parseInt(jTextID.getText()));
        nuevoInventario.setId_sucursal(Integer.parseInt(jTextSucursal.getText()));
        nuevoInventario.setCantidad_disponible(BigDecimal.valueOf(Double.parseDouble(jTcantidaddisponible.getText())));
        int id_materiaPrima = (int) jTableMateriaPrima.getValueAt(jTableMateriaPrima.getSelectedRow(), 0);
        nuevoInventario.setId_materia_prima(id_materiaPrima);
        
        
        persistencia.DAOInventarioMateriaPrimaImpl insertInventario = new persistencia.DAOInventarioMateriaPrimaImpl();
        try{
            insertInventario.registrar(nuevoInventario);
            //insertEmpleado1.registrar(nuevoEmpleado1);
        }catch(Exception ex){
            Logger.getLogger(EmpleadoV.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Ocurrió un error al registrar al Cliente", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBañadirActionPerformed

    private void jTextSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSucursalActionPerformed
        
    }//GEN-LAST:event_jTextSucursalActionPerformed

    private void jBmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodificarActionPerformed
        models.InventarioMateriaPrimaM modInventario = new models.InventarioMateriaPrimaM();
        modInventario.setId_inventario(Integer.parseInt(jTextID.getText()));
        modInventario.setId_sucursal(Integer.parseInt(jTextSucursal.getText()));
        modInventario.setCantidad_disponible(BigDecimal.valueOf(Double.parseDouble(jTcantidaddisponible.getText())));
        
        persistencia.DAOInventarioMateriaPrimaImpl modificarInventario = new persistencia.DAOInventarioMateriaPrimaImpl();
        try {
            modificarInventario.modificar(modInventario);
        } catch (Exception ex) {
            Logger.getLogger(ProductoV.class.getName()).log(Level.SEVERE, null, ex);
        }
         jBmodificar.setEnabled(false);
         jBeliminar.setEnabled(false);
         jBañadir.setEnabled(true);
         limpiarCampos();
    }//GEN-LAST:event_jBmodificarActionPerformed

    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed
        DAOInventarioMateriaPrimaImpl eliminarInventario = new DAOInventarioMateriaPrimaImpl();
        DefaultTableModel model = (DefaultTableModel) this.jTableInventario.getModel();
        for(int i : jTableInventario.getSelectedRows()){
            try {
                int empID =  (int)jTableInventario.getValueAt(1, 0);
                int sucID =  (int)jTableInventario.getValueAt(1, 1);
                eliminarInventario.eliminar(empID, sucID);
                model.removeRow(i);
            } catch (Exception ex) {
                Logger.getLogger(EmpleadoV.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        jBmodificar.setEnabled(false);
        jBeliminar.setEnabled(false);
        jBañadir.setEnabled(true);
        limpiarCampos();
    }//GEN-LAST:event_jBeliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatArcOrangeIJTheme.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventarioV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBañadir;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBmenu;
    private javax.swing.JButton jBmodificar;
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLbackground;
    private javax.swing.JLabel jLbarraSelecc;
    private javax.swing.JLabel jLlogo;
    private javax.swing.JLabel jLmenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPbackground;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableInventario;
    private javax.swing.JTable jTableMateriaPrima;
    private javax.swing.JTextField jTcantidaddisponible;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextField jTextSucursal;
    // End of variables declaration//GEN-END:variables
}
