package vista.operacion;

import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import javax.swing.table.DefaultTableModel;
import persistencia.DAOSucursalImpl;
import vista.inicio.MenuV;

public class SucursalV extends javax.swing.JFrame {
    // Atributos
    DAOSucursalImpl dao = new DAOSucursalImpl();
    
    public SucursalV() {
        initComponents();
        initStyles();
        loadTable();
    }

    private void initStyles() {
        this.jBmenu.putClientProperty("JButton.buttonType", "roundRect");
        this.jBsalir.putClientProperty("JButton.buttonType", "roundRect");
    }
    
    private void loadTable() {
        try {
            DefaultTableModel model = (DefaultTableModel) this.jTsucursal.getModel();
            dao.listar().forEach((suc) -> model.addRow(new Object[]{suc.getId_sucursal(), suc.getNombre(), suc.getDireccion(), suc.getCiudad(), suc.getTelefono()}));
            
        } catch (Exception e) {
            System.out.println("El siguiente error se ha suscitado: " + e.toString());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPbackground = new javax.swing.JPanel();
        jLlogo = new javax.swing.JLabel();
        jLbarraSelecc = new javax.swing.JLabel();
        jLsucursal = new javax.swing.JLabel();
        jBmenu = new javax.swing.JButton();
        jPtituloTabla = new javax.swing.JPanel();
        jLtituloTabla = new javax.swing.JLabel();
        jBsalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTsucursal = new javax.swing.JTable();
        jLbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPbackground.setBackground(new java.awt.Color(255, 255, 255));
        jPbackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.jpg"))); // NOI18N
        jPbackground.add(jLlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 96, 50));

        jLbarraSelecc.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLbarraSelecc.setForeground(new java.awt.Color(255, 255, 255));
        jLbarraSelecc.setText("____________________");
        jPbackground.add(jLbarraSelecc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 180, 20));

        jLsucursal.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLsucursal.setForeground(new java.awt.Color(255, 255, 255));
        jLsucursal.setText("Sucursal");
        jPbackground.add(jLsucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 170, 30));

        jBmenu.setBackground(new java.awt.Color(255, 102, 102));
        jBmenu.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jBmenu.setText("Menu");
        jBmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmenuActionPerformed(evt);
            }
        });
        jPbackground.add(jBmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 40, 160, 35));

        jPtituloTabla.setBackground(new java.awt.Color(0, 0, 0));

        jLtituloTabla.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLtituloTabla.setForeground(new java.awt.Color(255, 255, 255));
        jLtituloTabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLtituloTabla.setText("Lista de Sucursales");

        javax.swing.GroupLayout jPtituloTablaLayout = new javax.swing.GroupLayout(jPtituloTabla);
        jPtituloTabla.setLayout(jPtituloTablaLayout);
        jPtituloTablaLayout.setHorizontalGroup(
            jPtituloTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPtituloTablaLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLtituloTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPtituloTablaLayout.setVerticalGroup(
            jPtituloTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPtituloTablaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLtituloTabla)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPbackground.add(jPtituloTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 640, 30));

        jBsalir.setBackground(new java.awt.Color(255, 102, 102));
        jBsalir.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jBsalir.setText("SALIR");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });
        jPbackground.add(jBsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, 160, 35));

        jTsucursal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Listado", "Nombre", "Direccion", "Telefono", "Ciudad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTsucursal);
        if (jTsucursal.getColumnModel().getColumnCount() > 0) {
            jTsucursal.getColumnModel().getColumn(0).setResizable(false);
            jTsucursal.getColumnModel().getColumn(0).setPreferredWidth(1);
            jTsucursal.getColumnModel().getColumn(1).setResizable(false);
            jTsucursal.getColumnModel().getColumn(2).setResizable(false);
            jTsucursal.getColumnModel().getColumn(3).setResizable(false);
            jTsucursal.getColumnModel().getColumn(4).setResizable(false);
            jTsucursal.getColumnModel().getColumn(4).setPreferredWidth(1);
        }

        jPbackground.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 640, 290));

        jLbackground.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo_Gestion.jpg"))); // NOI18N
        jPbackground.add(jLbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmenuActionPerformed
        MenuV menu = new MenuV();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBmenuActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatArcOrangeIJTheme.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SucursalV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBmenu;
    private javax.swing.JButton jBsalir;
    private javax.swing.JLabel jLbackground;
    private javax.swing.JLabel jLbarraSelecc;
    private javax.swing.JLabel jLlogo;
    private javax.swing.JLabel jLsucursal;
    private javax.swing.JLabel jLtituloTabla;
    private javax.swing.JPanel jPbackground;
    private javax.swing.JPanel jPtituloTabla;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTsucursal;
    // End of variables declaration//GEN-END:variables
}
